package trackwareschoolbus.parentschool.API.enumApi;

/**
 * Created by  on 1/14/17.
 */

public enum EnumNameApi {
    LOG_IN,
    GET_SETTING,
    POST_SETTING,
    GTE_KIDS_LIST,
    GET_PARENT_NOTIFICATION,
    POST_PARENT_NOTIFICATION,
    GET_STUDENT,
    FORGET_PASSWORD,
    ABSENT,
    ABSENT_DRIVER_NOTIFICATION,
    CHANGE_LOCATION, REGISTER,
    GOOGLE_DISTANCE_TIME,
    PARENTS_KIDS_HISTORY,
    BUS_LOCATION, ROUND_STATUS,
    PUSH_NOTIFICATION, REGISTER_DIALOG,
    IS_STUDENT_SERVED,
    ACTIVATE_KID,
    GET_KIDS_TEACHER,
    GTE_KIDS_LIST_ABSENT,
    PRE_ARRIVE,
//    PARENT_IS_REGISTER,
    GET_MESSAGE_HISTORY
}
